apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  labels:
    app: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - name: httpd
        image: rdevops27/httpd:v1
        ports:
        - containerPort: 80

