apiVersion: v1
kind: Pod
metadata:
  name: health-check
spec:
  containers:
  - name: health
    image: rdevops27/health
    imagePullPolicy: Always
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
