apiVersion: v1
kind: ReplicationController
metadata:
  name: student-rc
spec:
  replicas: 2
  selector:
    app: studentapp
  template:
    metadata:
      name: student-rc
      labels:
        app: studentapp
    spec:
      containers:
      - name: tomcat
        image: rdevops27/sample:2.5
        ports:
        - containerPort: 8080
        
