apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: centos 
    name: test-container
    command: ["sleep"]
    args: ["1000"]
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4
